(() => {
"use strict";
const canvas=document.getElementById("crawlCanvas"),ctx=canvas.getContext("2d");
const sections=[
 {name:"ROLE",sub:"Define the agent",color:"#e9f4ff",words:["You are","SPIDER","an autonomous","AI agent"]},
 {name:"OBJECTIVE",sub:"What must be achieved",color:"#35e0ff",words:["Analyze","collect","connect","verify","deliver"]},
 {name:"CONTEXT",sub:"Relevant information",color:"#ff64d8",words:["Research","sources","evidence","signals"]},
 {name:"ROLES",sub:"Who does what",color:"#ffd166",words:["Planner","Crawler","Verifier","Synthesizer"]},
 {name:"RULES",sub:"Boundaries and constraints",color:"#2dd4bf",words:["Cite sources","Never guess","Ask when unclear"]},
 {name:"REVIEW",sub:"Quality gate",color:"#b79aff",words:["Check facts","Find gaps","Score confidence"]},
 {name:"START",sub:"Begin the task",color:"#ff9e45",words:["Initialize","crawl","inspect"]},
 {name:"SHIP",sub:"Verified result",color:"#ff64d8",words:["Clear answer","Traceable","ready to ship"]}
];
let W=0,H=0,dpr=1,t=0,sectionIndex=0,wordIndex=0,read=0,links=0,flags=0,lastEventAt=0,lastEventId="",socketState="CONNECTING";
let spider={x:0,y:0,tx:0,ty:0,phase:0,legs:16};
const tentacles=Array.from({length:22},(_,i)=>({angle:i*Math.PI*2/22,phase:Math.random()*6.28,state:"anchored",progress:1,anchorX:0,anchorY:0,wait:Math.random()*1.8}));
let locomotionPending=false,bodyPull=false,cycleClock=0;
const stars=Array.from({length:650},()=>({x:(Math.random()-.5)*5000,y:(Math.random()-.5)*3500,r:Math.random()*1.3+.2,a:Math.random()*.55+.12}));
const trails=[];let cameraX=0,cameraY=0;
const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);layout();}
function layout(){const mobile=W<700,top=48,bottom=18,areaH=Math.max(260,H-top-bottom),cols=mobile?2:4,rows=Math.ceil(sections.length/cols);sections.forEach((s,i)=>{const col=i%cols,row=Math.floor(i/cols);s.x=W*(col+.5)/cols;s.y=top+areaH*(row+.5)/rows;const cellW=W/cols;s.rx=Math.max(52,cellW*.43);s.ry=Math.min(49,areaH/rows*.43);});if(!spider.x){spider.x=W*.5;spider.y=top+areaH*.5;spider.tx=sections[0].x;spider.ty=sections[0].y;}}
function drawBackground(){ctx.fillStyle="#03050a";ctx.fillRect(0,0,W,H);ctx.save();for(const s of stars){const x=((W*.5+s.x-spider.x*.18)% (W+20)+(W+20))%(W+20)-10;const y=((H*.5+s.y-spider.y*.18)%(H+20)+(H+20))%(H+20)-10;ctx.globalAlpha=s.a*(.65+.35*Math.sin(t*.7+s.x*.02));ctx.fillStyle="#8bdfff";ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.restore();}
function drawCluster(s,i){const active=i===sectionIndex;ctx.save();ctx.translate(s.x,s.y);ctx.globalAlpha=active?1:.62;ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=active?1.2:.7;ctx.setLineDash(active?[]:[3,5]);ctx.beginPath();ctx.ellipse(0,0,s.rx,s.ry,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.font="700 10px monospace";ctx.textAlign="center";ctx.fillText(s.name,0,-s.ry+13);const cols=W<700?2:Math.min(3,s.words.length),cellW=(s.rx*1.72)/cols,rows=Math.ceil(s.words.length/cols),rowH=Math.min(24,(s.ry*1.25)/Math.max(1,rows));s.words.forEach((word,j)=>{const col=j%cols,row=Math.floor(j/cols),x=(col-(cols-1)/2)*cellW,y=-s.ry*.15+row*rowH+8;const isRead=i<sectionIndex||(i===sectionIndex&&j<wordIndex);ctx.font=(W<430?"9px":"10px")+" monospace";const labelW=Math.min(cellW-4,Math.max(38,ctx.measureText(word).width+12));ctx.globalAlpha=active?1:.72;ctx.fillStyle=isRead?s.color:"#07111b";ctx.strokeStyle=s.color;ctx.lineWidth=.7;ctx.beginPath();ctx.roundRect(x-labelW/2,y-8,labelW,17,4);ctx.fill();ctx.stroke();ctx.fillStyle=isRead?"#05080c":s.color;ctx.fillText(word,x,y+3,labelW-6);if(active&&j===wordIndex){ctx.globalAlpha=1;ctx.strokeStyle="#fff";ctx.lineWidth=1.4;ctx.beginPath();ctx.roundRect(x-labelW/2-2,y-10,labelW+4,21,5);ctx.stroke();}});ctx.restore();}
function curve(a,b,c,d,e,f,g,h){ctx.beginPath();ctx.moveTo(a,b);ctx.bezierCurveTo(c,d,e,f,g,h);ctx.stroke();}
function drawSpider(){cycleClock+=.016;const dx=spider.tx-spider.x,dy=spider.ty-spider.y,dist=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);if(locomotionPending&&!bodyPull&&!tentacles.some(l=>l.state==="reaching")){const limb=tentacles.find(l=>l.state==="anchored"&&l.wait<=0);if(limb){limb.angle=0;limb.targetReach=Math.min(180,Math.max(30,dist));limb.state="reaching";limb.progress=0;limb.anchorX=dx;limb.anchorY=dy;}}if(bodyPull){const step=reduced?.12:.035;spider.x+=dx*step;spider.y+=dy*step;if(dist<5){spider.x=spider.tx;spider.y=spider.ty;bodyPull=false;locomotionPending=false;trails.push({x:spider.x,y:spider.y,x2:spider.x+Math.cos(angle)*10,y2:spider.y+Math.sin(angle)*10,life:1,color:sections[sectionIndex].color});tentacles.forEach(l=>{l.state="anchored";l.progress=1;l.wait=.15+Math.random()*.45;});}}tentacles.forEach(l=>{l.wait=Math.max(0,l.wait-.016);if(l.state==="reaching"){l.progress=Math.min(1,l.progress+(reduced?.2:.075));if(l.progress>=1){l.state="anchored";bodyPull=true;}}});ctx.save();ctx.translate(spider.x,spider.y);ctx.rotate(angle);const pulse=Math.sin(t*9)*1.4;ctx.lineCap="round";for(let side of [-1,1])for(let i=0;i<8;i++){const rootX=side*5,rootY=(i-3.5)*2.1,reach=16+(i%3)*2.2,stride=Math.sin(t*7+i*1.7+side)*3,kneeX=side*(11+reach*.42),kneeY=rootY+stride,tipX=side*(21+reach)+stride*.25,tipY=rootY*2.5+Math.sin(t*5+i)*2;ctx.strokeStyle=i%3===0?"#ff64d8":"#35e0ff";ctx.lineWidth=1.05;curve(rootX,rootY,kneeX*.45,rootY-4,kneeX,kneeY,tipX,tipY);ctx.fillStyle="#c8f6ff";ctx.beginPath();ctx.arc(tipX,tipY,1.2,0,Math.PI*2);ctx.fill();}tentacles.forEach((l,i)=>{const radial=l.angle+Math.sin(t*1.8+l.phase)*.08,rootX=Math.cos(radial)*5,rootY=Math.sin(radial)*4,reach=18+(i%4)*3,extension=l.state==="reaching"?(l.targetReach||reach+11):reach,tx=Math.cos(radial)*extension,ty=Math.sin(radial)*extension,curveX=(rootX+tx)*.55-Math.sin(radial)*4,curveY=(rootY+ty)*.55+Math.cos(radial)*4;ctx.strokeStyle=l.state==="reaching"?"#ffffff":i%2?"rgba(255,100,216,.86)":"rgba(53,224,255,.86)";ctx.lineWidth=l.state==="reaching"?1.1:.72;ctx.beginPath();ctx.moveTo(rootX,rootY);ctx.quadraticCurveTo(curveX,curveY,tx,ty);ctx.stroke();ctx.fillStyle=l.state==="anchored"?"#d9faff":"#ffffff";ctx.beginPath();ctx.arc(tx,ty,l.state==="reaching"?1.5:.9,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#06121b";ctx.strokeStyle="#35e0ff";ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(-5,0,6,5,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(5,0,4.5,4,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#ff64d8";ctx.beginPath();ctx.arc(6,-1.5,1.2,0,Math.PI*2);ctx.arc(6,1.5,1.2,0,Math.PI*2);ctx.fill();ctx.restore();}
function frame(){t+=.016;drawBackground();cameraX+=(spider.x-W*.5-cameraX)*.08;cameraY+=(spider.y-H*.5-cameraY)*.08;ctx.save();ctx.translate(-cameraX,-cameraY);sections.forEach(drawCluster);drawTrails();drawSpider();ctx.restore();requestAnimationFrame(frame);}
function drawTrails(){for(let i=trails.length-1;i>=0;i--){const p=trails[i];p.life-=.012;if(p.life<=0){trails.splice(i,1);continue;}ctx.globalAlpha=Math.max(0,p.life)*.45;ctx.strokeStyle=p.color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x2,p.y2);ctx.stroke();}ctx.globalAlpha=1;}
function wordPoint(s,j){const cols=W<700?2:Math.min(3,s.words.length),cellW=(s.rx*1.72)/cols,rows=Math.ceil(s.words.length/cols),rowH=Math.min(24,(s.ry*1.25)/Math.max(1,rows)),col=j%cols,row=Math.floor(j/cols);return{x:s.x+(col-(cols-1)/2)*cellW,y:s.y-s.ry*.15+row*rowH+8};}
function targetWord(idx,wi){const s=sections[idx],p=wordPoint(s,Math.max(0,Math.min(wi,s.words.length-1)));spider.tx=p.x;spider.ty=p.y;locomotionPending=true;}
function mapNode(node,tool,eventType){const x=String(node||"").toUpperCase(),k=String(tool||"").toLowerCase(),z=(k+" "+String(eventType||"")).toLowerCase();if(["TASK","SEARCH","COLLECT","ANALYZE","CONNECT","VERIFY","PROCESS","RESULT","COMPLETE","ERROR","UNKNOWN"].includes(x))return ({TASK:0,SEARCH:1,COLLECT:2,ANALYZE:3,CONNECT:4,VERIFY:5,PROCESS:6,RESULT:7,COMPLETE:7,ERROR:5,UNKNOWN:5})[x];const exact={search:1,"browser.search":1,browser_search:1,deep_research:1,open:2,"browser.open":2,find:2,read:2,memory_search:2,memory_get:2,exec:6,write:6,edit:6,"todo.write":3,"subagent.spawn":3,create_options:7,"browser.spawn_task":0,"browser.steer_task":0,"browser.peek_task":0,"browser.list_tasks":0,"task.spawn":0,"task.steer":0,"task.peek":0,"task.list":0,connect:4,"browser.connect":4,auth:4,"browser.auth":4,login:4,"browser.login":4,oauth:4,"browser.oauth":4,db:5,"muse.db":5};if(Object.prototype.hasOwnProperty.call(exact,k))return exact[k];if(k.includes("search"))return 1;if(k.startsWith("browser."))return 2;if(k==="exec"||k==="edit"||k==="write")return 6;if(String(eventType||"").includes("TASK_"))return 0;return 5;}
function status(label,detail){const el=document.getElementById("agentStatus");el.textContent=label;el.style.color=label==="LIVE"?"#5ff0a4":label==="DISCONNECTED"?"#f87171":"#ffd166";document.getElementById("crawlLog").textContent=detail;}
function consumeEvent(raw){const e=raw&&raw.type==="spider_event"?(raw.event||raw.data||raw):raw;if(!e||typeof e!=="object")return;const typ=String(e.event_type||e.type||"");if(!["TOOL_STARTED","TOOL_COMPLETED","TOOL_FAILED","TASK_STARTED","TASK_COMPLETED","TASK_FAILED"].includes(typ))return;const id=e.event_id||e.id||[e.timestamp,e.tool,typ].join("|");if(id===lastEventId)return;lastEventId=id;lastEventAt=Date.now();const idx=typ==="TASK_COMPLETED"?7:typ==="TASK_FAILED"?5:mapNode(e.node,e.tool,typ),s=sections[idx];sectionIndex=idx;let wi=s.words.findIndex(w=>String(e.tool||"").toLowerCase()===w.toLowerCase());if(wi<0)wi=0;wordIndex=wi;if(typ==="TOOL_STARTED"||typ==="TASK_STARTED")read++;if(typ.includes("FAILED")||e.success===false)flags++;if(typ==="TOOL_STARTED")links++;targetWord(idx,wi);document.getElementById("activeTitle").textContent=s.name+" / "+(e.task||s.sub);document.getElementById("wordsRead").textContent=read;document.getElementById("linksCount").textContent=links;document.getElementById("flagsCount").textContent=flags;document.getElementById("sectionCount").textContent=idx+1;document.getElementById("networkLinks").textContent=links;document.getElementById("flagsBottom").textContent=flags;document.getElementById("heatFill").style.width=Math.min(100,read*4)+"%";document.getElementById("scoreNum").textContent="—";document.getElementById("frameNum").textContent=String(read).padStart(4,"0");document.querySelectorAll(".sectionRow").forEach((el,i)=>{el.classList.toggle("selected",i===idx);el.textContent=String(i+1).padStart(2,"0")+" "+sections[i].name+(i<idx?" · visited":i===idx?" · active":" · waiting");});document.querySelectorAll("#sectionTabs span").forEach((el,i)=>el.classList.toggle("active",i===idx));status("LIVE","REAL EVENT · "+typ+" · "+String(e.tool||e.node||"activity"));}
function connect(){const qs=new URLSearchParams(location.search),url=qs.get("ws")||((location.protocol==="https:"?"wss://":"ws://")+"spider-realtime-poc.sabuncolek1508.workers.dev/ws");try{const ws=new WebSocket(url);ws.onopen=()=>{socketState="CONNECTED";status("CONNECTED","Realtime connected; waiting for valid events.");};ws.onmessage=e=>{try{consumeEvent(JSON.parse(e.data));}catch(_){}};ws.onerror=()=>{socketState="ERROR";status("DISCONNECTED","WebSocket error; snapshot fallback remains enabled.");};ws.onclose=()=>{socketState="DISCONNECTED";status("DISCONNECTED","Realtime disconnected; snapshot fallback remains enabled.");setTimeout(connect,3000);};}catch(_){socketState="ERROR";setTimeout(connect,5000);}}
async function pollSnapshot(){try{const r=await fetch((new URLSearchParams(location.search).get("src")||"state.json")+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error();const d=await r.json();if(lastEventAt&&Date.now()-lastEventAt<15000)return;const stamp=Date.parse(d.updated_at||d.timestamp||"");const age=Number.isFinite(stamp)?Math.max(0,Date.now()-stamp):Infinity;const fresh=age<90000;const step=String(d.execution?.current_step||d.workflow?.active_node||"").toUpperCase(),idx=mapNode(step,d.execution?.current_tool,"");sectionIndex=idx;targetWord(idx,0);document.getElementById("activeTitle").textContent=sections[idx].name+" / "+(d.task?.title||sections[idx].sub);document.getElementById("sectionCount").textContent=idx+1;document.querySelectorAll(".sectionRow").forEach((el,i)=>{el.classList.toggle("selected",i===idx);el.textContent=String(i+1).padStart(2,"0")+" "+sections[i].name+(Array.isArray(d.workflow?.completed_nodes)&&d.workflow.completed_nodes.includes(sections[i].name)? " · done":i===idx?" · active":" · waiting");});document.querySelectorAll("#sectionTabs span").forEach((el,i)=>el.classList.toggle("active",i===idx));if(fresh){status("SNAPSHOT","FRESH SNAPSHOT · "+String(d.agent?.status||d.task?.status||"unknown").toUpperCase()+" · "+(step||"NO ACTIVE STEP"));}else{status("STALE","Snapshot is "+(Number.isFinite(age)?Math.round(age/60000)+" min old":"undated")+"; not evidence of current Muse activity.");}}catch(_){if(socketState!=="CONNECTED")status("DISCONNECTED","No valid snapshot received; waiting for connection.");}}
window.addEventListener("resize",resize);resize();frame();connect();pollSnapshot();setInterval(pollSnapshot,7000);setInterval(()=>{if(lastEventAt&&Date.now()-lastEventAt>60000&&socketState==="CONNECTED")status("INACTIVE","No valid events for "+Math.round((Date.now()-lastEventAt)/1000)+"s; connection may resume.");},5000);
document.getElementById("replayBtn").addEventListener("click",()=>{sectionIndex=0;wordIndex=0;spider.tx=sections[0].x;spider.ty=sections[0].y;status("REPLAY","Visual position reset; live telemetry remains authoritative.");});
})();