(() => {
"use strict";
const canvas=document.getElementById("crawlCanvas"),ctx=canvas.getContext("2d");
const sections=[
 {name:"ROLE",sub:"Define the agent",color:"#e9f4ff",words:["You are","SPIDER","an autonomous","AI agent"]},
 {name:"OBJECTIVE",sub:"What must be achieved",color:"#35e0ff",words:["Analyze","collect","connect","verify","deliver"]},
 {name:"CONTEXT",sub:"Relevant information",color:"#ff64d8",words:["Research","sources","evidence","signals"]},
 {name:"ROLES",sub:"Who does what",color:"#ffd166",words:["Planner","Crawler","Verifier","Synthesizer"]},
 {name:"RULES",sub:"Boundaries and constraints",color:"#2dd4bf",words:["Cite sources","Never guess","Ask when unclear"]},
 {name:"REVIEW",sub:"Quality gate",color:"#b79aff",words:["Check facts","Find gaps","Score confidence"]},
 {name:"START",sub:"Begin the task",color:"#ff9e45",words:["Initialize","crawl","inspect"]},
 {name:"SHIP",sub:"Verified result",color:"#ff64d8",words:["Clear answer","Traceable","ready to ship"]}
];
let W=0,H=0,dpr=1,t=0,sectionIndex=0,wordIndex=0,read=0,links=0,flags=0,lastEventAt=0,lastEventId="",socketState="CONNECTING";
let spider={x:0,y:0,tx:0,ty:0,phase:0,legs:16};
const stars=Array.from({length:650},()=>({x:(Math.random()-.5)*5000,y:(Math.random()-.5)*3500,r:Math.random()*1.3+.2,a:Math.random()*.55+.12}));
const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);layout();}
function layout(){const mobile=W<700;const top=mobile?75:100;const bottom=mobile?Math.min(255,H*.36):205;const areaH=Math.max(200,H-top-bottom);const cols=mobile?2:4;sections.forEach((s,i)=>{const col=i%cols,row=Math.floor(i/cols);s.x=W*(col+.5)/cols;s.y=top+areaH*(row+.45)/(mobile?4:3);});if(!spider.x){spider.x=W*.5;spider.y=top+areaH*.5;spider.tx=sections[0].x;spider.ty=sections[0].y;}}
function drawBackground(){ctx.fillStyle="#03050a";ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-spider.x*.18,-spider.y*.18);for(const s of stars){ctx.globalAlpha=s.a*(.65+.35*Math.sin(t*.7+s.x*20));ctx.fillStyle="#8bdfff";ctx.beginPath();ctx.arc(s.x*W,s.y*H,s.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.restore();}
function drawCluster(s,i){const active=i===sectionIndex;ctx.save();ctx.translate(s.x,s.y);ctx.globalAlpha=active?1:.58;ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=active?1.2:.7;ctx.setLineDash(active?[]:[3,5]);ctx.beginPath();ctx.ellipse(0,0,Math.max(60,s.words.join(" ").length*3.7),43,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.font="700 10px monospace";ctx.textAlign="center";ctx.fillText(s.name,0,-27);ctx.font="11px monospace";const count=s.words.length; s.words.forEach((word,j)=>{const angle=-Math.PI/2+(j/(count))*Math.PI*2;const x=Math.cos(angle)*48,y=Math.sin(angle)*27;const isRead=i<sectionIndex||(i===sectionIndex&&j<wordIndex);ctx.globalAlpha=active?1:.5;ctx.fillStyle=isRead?s.color:"#121c28";ctx.strokeStyle=s.color;ctx.beginPath();ctx.roundRect(x-word.length*3.4-7,y-8,word.length*6.8+14,17,4);ctx.fill();ctx.globalAlpha=active?1:.8;ctx.stroke();ctx.fillStyle=isRead?"#05080c":s.color;ctx.fillText(word,x,y+3);if(active&&j===wordIndex){ctx.globalAlpha=1;ctx.strokeStyle="#fff";ctx.lineWidth=1.4;ctx.beginPath();ctx.roundRect(x-word.length*3.4-9,y-10,word.length*6.8+18,21,5);ctx.stroke();}});ctx.restore();}
function curve(a,b,c,d,e,f,g,h){ctx.beginPath();ctx.moveTo(a,b);ctx.bezierCurveTo(c,d,e,f,g,h);ctx.stroke();}
function drawSpider(){const x=spider.x,y=spider.y;const dx=spider.tx-x,dy=spider.ty-y;const dist=Math.hypot(dx,dy);if(dist>2){spider.x+=dx*(reduced?.12:.035);spider.y+=dy*(reduced?.12:.035);}const angle=Math.atan2(spider.ty-y,spider.tx-x);ctx.save();ctx.translate(spider.x,spider.y);ctx.rotate(angle);const pulse=Math.sin(t*9)*1.7;
ctx.lineCap="round";for(let side of [-1,1])for(let i=0;i<8;i++){const u=i/7;const rootX=side*5,rootY=(i-3.5)*2.1;const reach=17+(i%3)*2.5;const stride=Math.sin(t*7+i*1.7+side)*4;const kneeX=side*(12+reach*.45),kneeY=rootY+stride;const tipX=side*(23+reach)+stride*.35,tipY=rootY*2.7+Math.sin(t*5+i)*3;ctx.strokeStyle=i%3===0?"#ff64d8":"#35e0ff";ctx.lineWidth=1.15;curve(rootX,rootY,kneeX*.45,rootY-4,kneeX,kneeY,tipX,tipY);ctx.fillStyle="#c8f6ff";ctx.beginPath();ctx.arc(tipX,tipY,1.35,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(53,224,255,.12)";ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(tipX,tipY);ctx.lineTo(tipX+side*5,tipY+7);ctx.stroke();}for(let k=0;k<11;k++){const side=k%2===0?1:-1;const phase=t*4+k*.83;const ax=Math.cos(phase)*7,ay=Math.sin(phase)*5;const tx=side*(30+(k%4)*5)+Math.sin(t*3+k)*8,ty=(k-5)*5+Math.cos(t*4+k)*9;ctx.strokeStyle=k%2?"rgba(255,100,216,.9)":"rgba(53,224,255,.9)";ctx.lineWidth=.75;curve(ax,ay,ax+side*12,ay-6,tx-side*8,ty+4,tx,ty);ctx.fillStyle="#eafaff";ctx.beginPath();ctx.arc(tx,ty,1,0,Math.PI*2);ctx.fill();}
ctx.fillStyle="#06121b";ctx.strokeStyle="#35e0ff";ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(-5,0,6,5,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(5,0,4.5,4,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#ff64d8";ctx.beginPath();ctx.arc(6,-1.5,1.2,0,Math.PI*2);ctx.arc(6,1.5,1.2,0,Math.PI*2);ctx.fill();ctx.restore();
ctx.strokeStyle="rgba(53,224,255,.25)";ctx.setLineDash([2,6]);ctx.beginPath();ctx.moveTo(spider.x,spider.y);ctx.lineTo(spider.tx,spider.ty);ctx.stroke();ctx.setLineDash([]);}
function frame(){t+=.016;drawBackground();sections.forEach(drawCluster);drawSpider();requestAnimationFrame(frame);}
function mapNode(node,tool,eventType){const x=String(node||"").toUpperCase(),z=(x+" "+String(tool||"")+" "+String(eventType||"")).toLowerCase();if(x==="TASK"||z.includes("task"))return 0;if(x==="SEARCH"||z.includes("search"))return 1;if(x==="COLLECT"||z.includes("open")||z.includes("read"))return 2;if(x==="ANALYZE"||z.includes("analy"))return 3;if(x==="CONNECT"||z.includes("connect")||z.includes("auth"))return 4;if(x==="VERIFY"||z.includes("verify")||z.includes("db"))return 5;if(x==="PROCESS"||z.includes("exec")||z.includes("edit")||z.includes("write"))return 6;if(x==="RESULT"||x==="COMPLETE"||z.includes("complete")||z.includes("result"))return 7;return 5;}
function status(label,detail){const el=document.getElementById("agentStatus");el.textContent=label;el.style.color=label==="LIVE"?"#5ff0a4":label==="DISCONNECTED"?"#f87171":"#ffd166";document.getElementById("crawlLog").textContent=detail;}
function consumeEvent(raw){const e=raw&&raw.type==="spider_event"?(raw.event||raw.data||raw):raw;if(!e||typeof e!=="object")return;const typ=String(e.event_type||e.type||"");if(!typ.startsWith("TOOL_")&&!typ.startsWith("TASK_"))return;const id=e.event_id||e.id||[e.timestamp,e.tool,typ].join("|");if(id===lastEventId)return;lastEventId=id;lastEventAt=Date.now();const idx=mapNode(e.node,e.tool,typ),s=sections[idx];let wi=s.words.findIndex(w=>String(e.tool||"").toLowerCase().includes(w.toLowerCase()));if(wi<0)wi=read%s.words.length;sectionIndex=idx;wordIndex=wi;read++;if(typ.includes("FAILED")||e.success===false)flags++;if(typ.includes("STARTED"))links++;spider.tx=s.x+(Math.random()-.5)*10;spider.ty=s.y+(Math.random()-.5)*8;document.getElementById("activeTitle").textContent=s.name+" / "+s.sub;document.getElementById("wordsRead").textContent=read;document.getElementById("linksCount").textContent=links;document.getElementById("flagsCount").textContent=flags;document.getElementById("sectionCount").textContent=idx+1;document.getElementById("networkLinks").textContent=links;document.getElementById("flagsBottom").textContent=flags;document.getElementById("heatFill").style.width=Math.min(100,read*4)+"%";document.getElementById("scoreNum").textContent="—";document.getElementById("frameNum").textContent=String(read).padStart(4,"0");document.querySelectorAll(".sectionRow").forEach((el,i)=>{el.classList.toggle("selected",i===idx);el.textContent=String(i+1).padStart(2,"0")+" "+sections[i].name+(i<idx?" · done":i===idx?" · active":" · waiting");});document.querySelectorAll("#sectionTabs span").forEach((el,i)=>el.classList.toggle("active",i===idx));status("LIVE","REAL EVENT · "+typ+" · "+String(e.tool||e.node||"activity"));}
function connect(){const qs=new URLSearchParams(location.search),url=qs.get("ws")||((location.protocol==="https:"?"wss://":"ws://")+"spider-realtime-poc.sabuncolek1508.workers.dev/ws");try{const ws=new WebSocket(url);ws.onopen=()=>{socketState="CONNECTED";status("CONNECTED","Realtime connected; waiting for valid events.");};ws.onmessage=e=>{try{consumeEvent(JSON.parse(e.data));}catch(_){}};ws.onerror=()=>{socketState="ERROR";status("DISCONNECTED","WebSocket error; snapshot fallback remains enabled.");};ws.onclose=()=>{socketState="DISCONNECTED";status("DISCONNECTED","Realtime disconnected; snapshot fallback remains enabled.");setTimeout(connect,3000);};}catch(_){socketState="ERROR";setTimeout(connect,5000);}}
async function pollSnapshot(){try{const r=await fetch((new URLSearchParams(location.search).get("src")||"state.json")+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error();const d=await r.json();if(lastEventAt&&Date.now()-lastEventAt<15000)return;const step=String(d.execution?.current_step||d.workflow?.active_node||"").toUpperCase(),idx=mapNode(step,d.execution?.current_tool,d.task?.status);document.getElementById("activeTitle").textContent=sections[idx].name+" / "+(d.task?.title||sections[idx].sub);status("SNAPSHOT","STATE SNAPSHOT · "+String(d.agent?.status||d.task?.status||"unknown").toUpperCase()+" · "+(step||"NO ACTIVE STEP"));}catch(_){if(socketState!=="CONNECTED")status("DISCONNECTED","No valid snapshot received; waiting for connection.");}}
window.addEventListener("resize",resize);resize();frame();connect();pollSnapshot();setInterval(pollSnapshot,7000);setInterval(()=>{if(lastEventAt&&Date.now()-lastEventAt>60000&&socketState==="CONNECTED")status("INACTIVE","No valid events for "+Math.round((Date.now()-lastEventAt)/1000)+"s; connection may resume.");},5000);
document.getElementById("replayBtn").addEventListener("click",()=>{sectionIndex=0;wordIndex=0;spider.tx=sections[0].x;spider.ty=sections[0].y;status("REPLAY","Visual position reset; live telemetry remains authoritative.");});
})();